
### Kinematic configuration parameter

# Debug mode
activate_output: true
activate_debug_output: false
activate_controller_node_output: true
plotting_result: true

# Clock frequency //hz
clock_frequency: 20

#road parameters
n_points_spline: 3

#Optimal control problem dimensions
state_dim: 13
control_dim: 3

#Inputs and output topics topic
output_cmd: '/jackal_velocity_controller/cmd_vel'
robot_state_topic: '/robot_state'

# Kinematic chain parameter
robot_base_link: base_link
target_frame: odom
tracking_frame: odom

# Weight on the slack variable for collision collision
slack_weight: 10000
repulsive_weight: 0.1
reference_velocity: 0.5

# Parameters for collision constraints
obstacles:
      n_obstacles: 4
      sub_ellipse_topic: ellipse_objects_feed
      n_discs: 1
      ego_l: 0.5
      ego_w: 0.4

constraints:
     velocity_constraints:
           min: [-1, -1]
           max: [1,1]
     #orientation_constraints:

acado_config:
     max_num_iteration: 70
     kkt_tolerance: 1e-3
     integrator_tolerance: 1e-3
     start_time_horizon: 0.0
     end_time_horizon: 5.0 # 5.0  # control and prediction horizon
     discretization_intervals: 50
     sampling_time: 0.1
     weight_factors:
           contour_weight_factors:
                #always 6 component 3 linear/position and 3 angular/Euler angle
                [1.0, 1.0]
           control_weight_factors:
                # same as degree of freedom
                [1.0, 1.0]
